permissions:
  checks: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x' # I picked LTS
        - name: Install dependencies
          run: dotnet restore
        - name: Test with dotnet
          run: dotnet test --logger trx --results-directory "TestResults"
        - name: Upload dotnet test results
          uses: actions/upload-artifact@v4
          with:
            name: dotnet-results
            path: TestResults
          # Use always() to always run this step to publish test results when there are test failures
          if: ${{ always() }}
        - name: Test Reporter
          uses: dorny/test-reporter@v1
          if: ${{ always() }}
          with:
            name: dotnet Tests
            path: "**/*.trx"
            reporter: dotnet-trx
            fail-on-error: true
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker build . -t iamdavidfrancis/dotnet-docker-sample:latest
            - name: Log into Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            - name: Push the container to Docker Hub
              run: docker push iamdavidfrancis/dotnet-docker-sample